<?php return array(
    'APP_NAME' => 'Laravel Interview MT',
    'MAIL_MAILER' => 'smtp',
    'MAIL_HOST' => 'smtp.gmail.com',
    'MAIL_PORT' => '587',
    'MAIL_USERNAME' => 'yoursmtpemail',
    'MAIL_PASSWORD' => 'yoursmtppassword',
    'MAIL_ENCRYPTION' => 'tls',
    'MAIL_FROM_ADDRESS' => 'noreply@anydomian.com',
    'MAIL_FROM_NAME' => 'noreply@anydomian.com',
    'DB_CONNECTION' => 'mysql',
    'DB_HOST' => 'localhost',
    'DB_PORT' => '3306',
    'DB_DATABASE' => 'laravel_interview_mt',
    'DB_USERNAME' => 'root',
    'DB_PASSWORD' => '',
);
